### ISSUE TITLE
Configuring web site fails

### ISSUE THREAD

**Issue by marcoooo** [prestaconcept/open-source-management#36]
Hi, just installed your CMS on my local machine, setup my first website as follow :+1: 

```
presta_cms_core:
    default_website: /website/carodessine
    default_locale: fr
    websites:
        carodessine:
            path: /website/carodessine
            hosts:
                dev:
                    fr:
                        locale: fr
                        host: www.carodessine.local
                prod:
                    fr:
                        locale: fr
                        host: www.carodessine.com
```

First, This website doesn't show in admin website list page http://www.carodessine.local/admin/fr/presta/cmscore/website/list?tl=fr
same result with app_dev.php page.

Should I launch a command to register myweb site in phpcr ?

Thanxs for the job done !

Marc
